package app.quire.android.ui.theme

import androidx.annotation.DrawableRes
import androidx.compose.foundation.layout.size
import androidx.compose.material3.Icon
import androidx.compose.runtime.Composable
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.unit.Dp
import androidx.compose.ui.unit.dp
import app.quire.android.R

/**
 * Quire's icons.
 *
 * The handoff ships no icon assets — every glyph in the prototype is a bare div with
 * a border, and it says outright to replace them with a real icon system. This is
 * that system: [Lucide](https://lucide.dev), ISC licensed, 24px grid, 2px strokes
 * with round caps and joins.
 *
 * Only the icons Quire actually uses are bundled, as vector drawables generated by
 * `scripts/generate-icons.py`. Lucide is not a Gradle dependency: seventeen icons is
 * a few kilobytes, while the obvious alternative (`material-icons-extended`) is
 * megabytes and has been deprecated by Google. Nothing is fetched at build time and
 * nothing at runtime, which is also what an offline-first app should be able to say.
 *
 * Names here are what the icon *means*, not what Lucide calls it. A use site asking
 * for [Contents] should not have to know that the drawing is a list, and swapping
 * the whole family later is then a change to this file rather than to thirty call
 * sites.
 */
object QuireIcons {

    // Navigation.
    @DrawableRes val Library = R.drawable.ic_library
    @DrawableRes val Bookmarks = R.drawable.ic_bookmark
    @DrawableRes val Settings = R.drawable.ic_settings

    // Movement between screens.
    @DrawableRes val Back = R.drawable.ic_chevron_left
    @DrawableRes val Forward = R.drawable.ic_chevron_right

    // Actions.
    @DrawableRes val Add = R.drawable.ic_plus
    @DrawableRes val Bookmark = R.drawable.ic_bookmark
    @DrawableRes val Share = R.drawable.ic_share_2
    @DrawableRes val Contents = R.drawable.ic_list
    @DrawableRes val Typography = R.drawable.ic_type
    @DrawableRes val Done = R.drawable.ic_check
    @DrawableRes val Save = R.drawable.ic_download
    @DrawableRes val Message = R.drawable.ic_send
    @DrawableRes val Story = R.drawable.ic_image
    @DrawableRes val More = R.drawable.ic_more_horizontal
    @DrawableRes val Copy = R.drawable.ic_copy
    @DrawableRes val Highlight = R.drawable.ic_highlighter
    @DrawableRes val Remove = R.drawable.ic_trash_2

    /** Writing something of your own against a passage. */
    @DrawableRes val Note = R.drawable.ic_square_pen

    // Handing a passage to another app. Named for the job rather than for the app
    // that does it, because Quire never does either itself — it has no network
    // permission and cannot. The drawing says what the reader is asking for; which
    // app answers is theirs to choose.
    @DrawableRes val Translate = R.drawable.ic_languages
    @DrawableRes val Dictionary = R.drawable.ic_book_a

    // Things the app talks about.
    @DrawableRes val Book = R.drawable.ic_book
    @DrawableRes val Streak = R.drawable.ic_flame
    @DrawableRes val Milestone = R.drawable.ic_award

    /**
     * The sizes an icon is allowed to be.
     *
     * A fixed scale rather than a free parameter: consistency across screens is the
     * entire reason for having an icon set, and it is lost the first time someone
     * needs 19.dp here and 21.dp there. Lucide's stroke scales with the icon, so
     * these stay optically even — 2px on the 24 grid is 1.5dp at [Medium], which is
     * the weight the handoff's own hand-drawn glyphs used.
     */
    object Size {
        /** Inline with text: chevrons on rows, markers in lists. */
        val Small: Dp = 16.dp

        /** The default. Navigation, top bars, action rows. */
        val Medium: Dp = 18.dp

        /** Standalone and tappable on its own: header buttons, share destinations. */
        val Large: Dp = 22.dp

        /** Empty states and other places an icon is the only thing on screen. */
        val Hero: Dp = 44.dp
    }
}

/**
 * Draws one icon, tinted to the current theme.
 *
 * The drawables carry a placeholder stroke colour; the tint here is what makes them
 * follow the palette, so an icon is never drawn with the raw resource. Pass null for
 * [contentDescription] when neighbouring text already names the control — a screen
 * reader announcing "Bookmark, Bookmark" is worse than it announcing it once.
 */
@Composable
fun QuireIcon(
    @DrawableRes icon: Int,
    contentDescription: String?,
    modifier: Modifier = Modifier,
    tint: Color = Quire.colors.ink,
    size: Dp = QuireIcons.Size.Medium,
) {
    Icon(
        painter = painterResource(icon),
        contentDescription = contentDescription,
        tint = tint,
        modifier = modifier.size(size),
    )
}
