import java.util.Properties

plugins {
    alias(libs.plugins.android.application)
    alias(libs.plugins.kotlin.compose)
    alias(libs.plugins.kotlin.serialization)
    alias(libs.plugins.ksp)
}

/**
 * The published version, and the only place it is decided.
 *
 * `defaultVersionName` is also spelled in `share/Links.kt` so the About row in
 * Settings can show it without a BuildConfig field, and `LinksTest` reads this file
 * back to prove the two agree — an About row that still says 0.1.0 after 0.2.0
 * shipped is wrong in the one place a reader looks before filing a bug report.
 *
 * Play rejects an upload whose versionCode it has already seen, so CI needs to move
 * it without a commit: -PquireVersionCode / QUIRE_VERSION_CODE override, and the
 * literal below stays the human-readable default.
 */
val defaultVersionCode = 1
val defaultVersionName = "0.1.0"

fun overridden(property: String, environment: String): String? =
    (providers.gradleProperty(property).orNull ?: System.getenv(environment))
        ?.takeIf { it.isNotBlank() }

val quireVersionCode: Int = overridden("quireVersionCode", "QUIRE_VERSION_CODE")
    ?.toInt() ?: defaultVersionCode
val quireVersionName: String = overridden("quireVersionName", "QUIRE_VERSION_NAME")
    ?: defaultVersionName

/**
 * Release signing credentials, which never live in this repository.
 *
 * `keystore.properties` is gitignored; the environment variables are for CI, which
 * has no checkout to put a file in. A relative `storeFile` resolves against the repo
 * root, because that is where `keystore.properties` sits and a path relative to
 * anything else is a guess.
 *
 * When any of the four is missing the release signing config is not created at all,
 * rather than falling back to the debug key. A debug-signed artifact that reaches a
 * tester track cannot be replaced by a properly signed one later — Play pins the
 * signing identity of an application id forever.
 */
val keystoreProperties = Properties().apply {
    val file = rootProject.file("keystore.properties")
    if (file.exists()) file.inputStream().use(::load)
}

fun signingSecret(property: String, environment: String): String? =
    (keystoreProperties.getProperty(property) ?: System.getenv(environment))
        ?.takeIf { it.isNotBlank() }

val releaseStoreFile = signingSecret("storeFile", "QUIRE_KEYSTORE")
val releaseStorePassword = signingSecret("storePassword", "QUIRE_KEYSTORE_PASSWORD")
val releaseKeyAlias = signingSecret("keyAlias", "QUIRE_KEY_ALIAS")
val releaseKeyPassword = signingSecret("keyPassword", "QUIRE_KEY_PASSWORD")

val canSignRelease: Boolean = releaseStoreFile != null && releaseStorePassword != null &&
    releaseKeyAlias != null && releaseKeyPassword != null

/**
 * R8 is off unless asked for. See docs/release.md for the reasoning in full; the
 * short version is that PdfBox-Android resolves fonts and codecs reflectively and
 * its failure mode under shrinking is a book that imports to an empty page, not a
 * build error. The keep rules are written and committed, so turning it on is
 * `-PquireMinify=true` plus one import of a real PDF on a real device.
 */
val quireMinify: Boolean = overridden("quireMinify", "QUIRE_MINIFY").toBoolean()

/**
 * The fixture corpus is generated by :core (Apache PDFBox needs java.awt, so it
 * cannot run on device) and packaged into the test APK as assets.
 * A plain File, not a Provider: AGP 9's SourceSet API rejects Providers.
 */
val fixtureAssets: java.io.File = rootProject.layout.projectDirectory.asFile
    .resolve("core/build/generated/fixtureAssets")

android {
    namespace = "app.quire.android"
    compileSdk = 37
    compileSdkMinor = 2

    defaultConfig {
        applicationId = "app.quire.android"
        minSdk = 26
        // compileSdk is 37 because Compose requires it. targetSdk stays at 36
        // because Robolectric 4.16 emulates no higher, and JVM-side Android tests
        // are worth more than targeting the very newest API.
        targetSdk = 36
        versionCode = quireVersionCode
        versionName = quireVersionName
        testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
    }

    signingConfigs {
        // Created only when all four credentials arrived. Absent is a valid state:
        // anyone can clone this repo and build, run and test the debug app without
        // ever having made a keystore.
        if (canSignRelease) {
            create("release") {
                storeFile = rootProject.file(releaseStoreFile!!)
                storePassword = releaseStorePassword
                keyAlias = releaseKeyAlias
                keyPassword = releaseKeyPassword
            }
        }
    }

    buildTypes {
        getByName("release") {
            isDebuggable = false
            isMinifyEnabled = quireMinify
            // Resource shrinking needs code shrinking; AGP fails the build if it is
            // asked for alone, so the two follow the same flag.
            isShrinkResources = quireMinify
            proguardFiles(
                getDefaultProguardFile("proguard-android-optimize.txt"),
                "proguard-rules.pro",
            )
            signingConfig = signingConfigs.findByName("release")
        }
    }

    buildFeatures { compose = true }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_17
        targetCompatibility = JavaVersion.VERSION_17
    }

    // Apache PDFBox (used only to author test fixtures) ships META-INF entries that
    // collide with its own fontbox jar when packaged into the test APK.
    packaging {
        resources {
            excludes += setOf(
                "META-INF/DEPENDENCIES",
                "META-INF/LICENSE",
                "META-INF/LICENSE.txt",
                "META-INF/NOTICE",
                "META-INF/NOTICE.txt",
                "META-INF/INDEX.LIST",
            )
        }
    }

    sourceSets {
        getByName("androidTest") {
            assets.srcDir(fixtureAssets)
        }
    }

    testOptions {
        unitTests {
            isIncludeAndroidResources = true
        }
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    implementation(project(":core"))
    // :core exposes @Serializable model types, so :app needs the runtime too.
    implementation(libs.kotlinx.serialization.json)
    implementation(libs.kotlinx.coroutines.core)

    implementation(libs.room.runtime)
    implementation(libs.room.ktx)
    ksp(libs.room.compiler)

    implementation(libs.work.runtime.ktx)
    implementation(libs.pdfbox.android)

    implementation(platform(libs.compose.bom))
    implementation(libs.compose.ui)
    implementation(libs.compose.material3)
    implementation(libs.activity.compose)
    implementation(libs.lifecycle.viewmodel.compose)

    // Robolectric is JUnit 4 only, so :app runs JUnit 4 while :core runs JUnit 5.
    testImplementation(kotlin("test"))
    testImplementation(libs.junit4)
    testImplementation(libs.robolectric)
    testImplementation(libs.androidx.test.core)
    testImplementation(libs.room.testing)
    testImplementation(libs.work.testing)
    // The same fixture corpus :core is tested against. Fixtures are authored with
    // Apache PDFBox and read back with PdfBox-Android, so the writer and the reader
    // under test are independent implementations.
    testImplementation(testFixtures(project(":core")))
    testImplementation(libs.pdfbox)

    // Instrumented tests. PdfRenderer and ML Kit are native-backed and cannot run
    // under Robolectric, so their coverage lives on a real device image.
    androidTestImplementation(libs.junit4)
    androidTestImplementation(libs.androidx.test.runner)
    androidTestImplementation(libs.androidx.test.junit)
    androidTestImplementation(libs.androidx.test.core)
    androidTestImplementation(libs.kotlinx.coroutines.core)
}

/**
 * Release tasks stop here when there is nothing to sign with.
 *
 * Without this the build succeeds and writes `app-release-unsigned.aab`, which the
 * Play Console rejects on upload — at the end of the slowest part of the process,
 * with a message about the artifact rather than about the four values that were
 * never set. Failing at the task that needed them says what to do instead.
 */
tasks.matching { it.name == "assembleRelease" || it.name == "bundleRelease" }
    .configureEach {
        doFirst {
            check(canSignRelease) {
                """
                |Cannot sign the release: no keystore credentials.
                |
                |Create $rootDir/keystore.properties (it is gitignored) with:
                |  storeFile=/absolute/path/to/quire-upload.jks
                |  storePassword=...
                |  keyAlias=quire-upload
                |  keyPassword=...
                |
                |or export QUIRE_KEYSTORE, QUIRE_KEYSTORE_PASSWORD, QUIRE_KEY_ALIAS
                |and QUIRE_KEY_PASSWORD. docs/release.md has the keytool command.
                """.trimMargin()
            }
        }
    }

// Apache PDFBox must not reach the device: it needs java.awt. Fixtures arrive as
// pre-built assets instead.
tasks.matching {
    it.name.contains("AndroidTest") && (it.name.startsWith("merge") || it.name.startsWith("generate"))
}.configureEach { dependsOn(":core:generateFixtureAssets") }
