#!/usr/bin/env python3
"""Render the landing site's generated pages.

Run from the repo root:

    python3 scripts/build-site.py

Today that means one page: `site/privacy.html`, rendered from
`docs/privacy-policy.md`. The policy has to exist in two places — Google Play demands
a public URL, and the repository should carry the document it is actually shipping —
and two hand-maintained copies of a legal text is how a stale privacy policy gets
published. There is one source; this makes the other.

The Markdown subset is hand-rolled rather than imported. Folio takes no dependencies
it does not need, and this file only has to understand the constructs the policy
actually uses — headings, paragraphs, lists, block quotes, tables, rules, and inline
emphasis, code and links. Anything outside that is a reason to simplify the document
rather than to grow the converter, so unknown block syntax raises instead of being
silently passed through as text.
"""
import html
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SOURCE = ROOT / "docs" / "privacy-policy.md"
OUTPUT = ROOT / "site" / "privacy.html"

# The page frame. Deliberately the same palette and type stack as site/index.html,
# and deliberately loading nothing from anywhere else — see the comment there.
PAGE = """<!doctype html>
<!--
  GENERATED — do not edit this file.

  Rendered from docs/privacy-policy.md by scripts/build-site.py. Edit the policy and
  re-run the script; a change made here is lost on the next deploy, and a privacy
  policy that says two different things in two places is worse than one that is
  merely out of date.
-->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{title} — Folio</title>
<meta name="description" content="Folio collects nothing. It has no account, no analytics and no INTERNET permission.">
<link rel="icon" href="assets/icon.png">
<style>
  :root {{
    --bg:#FDF9F6; --bg-alt:#F7EFE7; --ink:#111B28; --muted:#6A727D;
    --border:#E7DDD2; --accent:#214F7C;
    --serif:"Iowan Old Style","Palatino Linotype",Palatino,"Source Serif 4",Georgia,serif;
    --sans:system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",Arial,sans-serif;
  }}
  @media (prefers-color-scheme: dark) {{
    :root {{
      --bg:#1D1E20; --bg-alt:#26282B; --ink:#D0D1D3; --muted:#8E9298;
      --border:#34373B; --accent:#7FA8D4;
    }}
  }}
  * {{ box-sizing:border-box; }}
  body {{
    margin:0; background:var(--bg); color:var(--ink);
    font-family:var(--sans); font-size:17px; line-height:1.7;
    -webkit-font-smoothing:antialiased;
  }}
  .wrap {{ max-width:760px; margin:0 auto; padding:0 24px 72px; }}
  header {{ padding:28px 0; }}
  .brand {{ display:inline-flex; align-items:center; gap:12px; text-decoration:none; color:inherit; }}
  .brand img {{ width:32px; height:32px; border-radius:8px; display:block; }}
  .brand span {{ font-family:var(--serif); font-size:21px; }}
  h1 {{ font-family:var(--serif); font-weight:400; font-size:clamp(2rem,5vw,2.8rem);
       letter-spacing:-0.02em; line-height:1.15; margin:24px 0 8px; }}
  h2 {{ font-family:var(--serif); font-weight:400; font-size:1.5rem;
       letter-spacing:-0.01em; margin:44px 0 10px; }}
  h3 {{ font-size:1.08rem; margin:32px 0 8px; }}
  h4 {{ font-size:1rem; margin:24px 0 6px; }}
  p, li {{ color:var(--ink); }}
  a {{ color:var(--accent); }}
  code {{
    font-family:ui-monospace,SFMono-Regular,Menlo,monospace; font-size:0.9em;
    background:var(--bg-alt); border:1px solid var(--border);
    border-radius:5px; padding:1px 6px;
  }}
  blockquote {{
    margin:24px 0; padding:14px 20px; border-left:3px solid var(--border);
    background:var(--bg-alt); border-radius:0 10px 10px 0; color:var(--muted);
  }}
  blockquote p {{ color:inherit; margin:0 0 8px; }}
  blockquote p:last-child {{ margin-bottom:0; }}
  hr {{ border:0; border-top:1px solid var(--border); margin:44px 0; }}
  .table-scroll {{ overflow-x:auto; margin:22px 0; }}
  table {{ border-collapse:collapse; width:100%; font-size:15.5px; }}
  th, td {{ text-align:left; padding:10px 14px; border-bottom:1px solid var(--border);
           vertical-align:top; }}
  th {{ color:var(--muted); font-weight:600; font-size:14px; }}
  footer {{ border-top:1px solid var(--border); margin-top:56px; padding-top:26px;
           color:var(--muted); font-size:14.5px; }}
  footer a {{ color:var(--muted); }}
</style>
</head>
<body>
<div class="wrap">
<header>
  <a class="brand" href="./"><img src="assets/icon.png" alt=""><span>Folio</span></a>
</header>
{body}
<footer>
  <a href="./">Back to Folio</a> ·
  <a href="https://github.com/gajanansr/folio">Source on GitHub</a>
</footer>
</div>
</body>
</html>
"""


def inline(text: str) -> str:
    """Emphasis, code, and links — applied to already-escaped text.

    Code spans are extracted first and put back last, so a backtick span containing
    something that looks like emphasis (``*`` in a glob, say) is left alone.
    """
    spans: list[str] = []

    def stash(match: re.Match) -> str:
        spans.append(match.group(1))
        return f"\x00{len(spans) - 1}\x00"

    text = re.sub(r"`([^`]+)`", stash, text)
    text = html.escape(text, quote=False)

    text = re.sub(r"\[([^\]]+)\]\(([^)]+)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"<(https?://[^>]+)>", r'<a href="\1">\1</a>', text)
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<!\*)\*([^*]+)\*(?!\*)", r"<em>\1</em>", text)

    return re.sub(
        r"\x00(\d+)\x00",
        lambda m: f"<code>{html.escape(spans[int(m.group(1))], quote=False)}</code>",
        text,
    )


def render(markdown: str) -> tuple[str, str]:
    """Returns (title, body html)."""
    lines = markdown.splitlines()
    out: list[str] = []
    title = "Privacy Policy"
    i = 0

    while i < len(lines):
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        if stripped.startswith("#"):
            level = len(stripped) - len(stripped.lstrip("#"))
            text = stripped[level:].strip()
            if level == 1:
                title = re.sub(r"^Folio\s*[—-]\s*", "", text)
            out.append(f"<h{level}>{inline(text)}</h{level}>")
            i += 1

        elif set(stripped) <= {"-"} and len(stripped) >= 3:
            out.append("<hr>")
            i += 1

        elif stripped.startswith("|"):
            rows = []
            while i < len(lines) and lines[i].strip().startswith("|"):
                rows.append([c.strip() for c in lines[i].strip().strip("|").split("|")])
                i += 1
            # Row two of a Markdown table is the alignment rule, not data.
            head, body_rows = rows[0], rows[2:]
            cells = "".join(f"<th>{inline(c)}</th>" for c in head)
            table = [f'<div class="table-scroll"><table><thead><tr>{cells}</tr></thead><tbody>']
            for row in body_rows:
                table.append("<tr>" + "".join(f"<td>{inline(c)}</td>" for c in row) + "</tr>")
            table.append("</tbody></table></div>")
            out.append("".join(table))

        elif stripped.startswith(">"):
            quoted = []
            while i < len(lines) and lines[i].strip().startswith(">"):
                quoted.append(lines[i].strip().lstrip(">").strip())
                i += 1
            paragraphs = " ".join(quoted).split("  ")
            inner = "".join(f"<p>{inline(p.strip())}</p>" for p in paragraphs if p.strip())
            out.append(f"<blockquote>{inner}</blockquote>")

        elif re.match(r"^[-*]\s+|^\d+\.\s+", stripped):
            ordered = bool(re.match(r"^\d+\.\s+", stripped))
            items: list[str] = []
            while i < len(lines) and lines[i].strip():
                current = lines[i].strip()
                if re.match(r"^[-*]\s+|^\d+\.\s+", current):
                    items.append(re.sub(r"^([-*]|\d+\.)\s+", "", current))
                else:
                    # A wrapped continuation line belongs to the item above it.
                    items[-1] += " " + current
                i += 1
            tag = "ol" if ordered else "ul"
            out.append(f"<{tag}>" + "".join(f"<li>{inline(x)}</li>" for x in items) + f"</{tag}>")

        else:
            paragraph: list[str] = []
            while i < len(lines) and lines[i].strip() and not re.match(
                r"^\s*(#|>|\||[-*]\s|\d+\.\s)", lines[i]
            ):
                paragraph.append(lines[i].strip())
                i += 1
            out.append(f"<p>{inline(' '.join(paragraph))}</p>")

    return title, "\n".join(out)


def main() -> int:
    if not SOURCE.exists():
        print(f"missing {SOURCE}", file=sys.stderr)
        return 1

    # A placeholder that reaches the published page is worse than a build failure:
    # nobody re-reads a privacy policy after the first time they host it.
    text = SOURCE.read_text(encoding="utf-8")
    for placeholder in ("[CONTACT EMAIL]", "TODO", "FILL IN"):
        if placeholder in text:
            print(f"{SOURCE}: still contains {placeholder!r}", file=sys.stderr)
            return 1

    title, body = render(text)
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(PAGE.format(title=html.escape(title), body=body), encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)} ({len(body.splitlines())} blocks)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
